### ISSUE TITLE
Depndency Issue With NotificationHandler

### ISSUE THREAD

**Issue by AhmedBoody** [evolutionary-architecture/evolutionary-architecture-by-example#158]
I run chapter 3 solution 

I got this issue when hit end-point sign the contract

 EvolutionaryArchitecture.Fitnet.Common.Api.ErrorHandling.GlobalExceptionHandler[0]
      An error occurred.
      System.InvalidOperationException: Cannot resolve 'System.Collections.Generic.IEnumerable`1[MediatR.INotificationHandler`1[EvolutionaryArchitecture.Fitnet.Contracts.IntegrationEvents.ContractSignedEvent]]' from root provider because it requires scoped service 'EvolutionaryArchitecture.Fitnet.Passes.DataAccess.Database.PassesPersistence'.
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at MediatR.Wrappers.NotificationHandlerWrapperImpl`1.Handle(INotification notification, IServiceProvider serviceFactory, Func`4 publish, CancellationToken cancellationToken)
         at MediatR.Mediator.PublishNotification(INotification notification, CancellationToken cancellationToken)
         at MediatR.Mediator.Publish[TNotification](TNotification notification, CancellationToken cancellationToken)
         at EvolutionaryArchitecture.Fitnet.Common.Infrastructure.Events.EventBus.InMemory.InMemoryEventBus.PublishAsync[TEvent](TEvent event, CancellationToken cancellationToken)
         at EvolutionaryArchitecture.Fitnet.Contracts.Application.Sign.SignContractCommandHandler.Handle(SignContractCommand command, CancellationToken cancellationToken) in C:\Me\fitnetss-MM\Contracts\Fitnet.Contracts.Application\Sign\SignContractCommandHandler.cs:line 27
         at MediatR.Wrappers.RequestHandlerWrapperImpl`1.<>c__DisplayClass1_0.<<Handle>g__Handler|0>d.MoveNext()
      --- End of stack trace from previous location ---

**Comment by kamilbaczek** [comment]
thanks for reporting. I will check it today

**Comment by AhmedBoody** [comment]
> thanks for reporting. I will check it today

by the way I could by pass it by register DBContext & DBContextOptions as transient but this is not solution btw

**Comment by kamilbaczek** [comment]
I was able to reproduce this issue but in chapter 2 not 3
